# Spring Boot configuration
spring:
  profiles:
    active: development
# Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/appdb?createDatabaseIfNotExist=true
    username: qrok
    password: qrok
# JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    # Show or not log for each sql query
    show-sql: true
    database: mysql
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: false
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: DEBUG
# Server configuration
server:
  port: 8088
  sessionTimeout: 30
# Security configuration
security:
  user:
    name: qrok
    password: qrok